name: Android

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gettext
      run: sudo apt-get update && sudo apt-get install -y gettext

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    # CMake version 3.21.3 causes gradle to throw a NullPointerException during the build
    # Removing it will cause gradle to fall back on 3.18.1 installed by the Android SDK
    - name: Create Build Environment
      run: rm /usr/local/bin/cmake

    - name: Cache CMake build folder
      uses: actions/cache@v2
      with:
        path: android-project/app/.cxx
        key: android-cmake-v2-${{ github.sha }}
        restore-keys: android-cmake-v2-

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: cd android-project && ./gradlew assembleDebug

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      with:
        name: devilutionx-debug.apk
        path: android-project/app/build/outputs/apk/debug/app-debug.apk
